---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app1
  namespace: default  
  labels:
    app.kubernetes.io/name: web-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-app1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-app1
    spec:
      containers:
      - image: nginx
        name: web-app1
        volumeMounts:
        - name: index-html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.5"
          limits:
            memory: "128Mi"
            cpu: "0.5"          
      volumes:
      - name: index-html-volume
        configMap:
          name: index-html-config          
      dnsConfig:
        options:
          - name: ndots
            value: "2"