---
apiVersion: v1
kind: Service
metadata:
  name: web-app1
  namespace: default  
  labels:
    app.kubernetes.io/name: web-app1
spec:
  selector:
    app.kubernetes.io/name: web-app1
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  # type: LoadBalancer