apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: with-recv
  namespace: metallb-system
  # namespace: frr-k8s-system
spec:
  bgp:
    routers:
    # - asn: 64512
    #   neighbors:
    #   - address: 172.18.0.1
    #     asn: 64512
    #     toReceive:
    #       allowed:
    #         mode: all
      - asn: 65000
        # routerID: 10.0.0.0
        neighbors:
          # ToR0 (ASN 65010)
          # - address: 172.20.20.6  # IP address of ToR0
          # - address: 10.0.1.1  # IP address of ToR0
          - address: 10.0.1.2  # IP address of ToR0
            asn: 65010           # ASN of ToR0
            # ebgpMultihop: 2
            # bfdProfile: testbfdprofile
            toReceive:
              allowed:
                mode: all        # Accept all prefixes from ToR0

          # ToR1 (ASN 65011)
          # - address: 172.20.20.8  # IP address of ToR1
          # - address: 10.0.2.1  # IP address of ToR1
          - address: 10.0.2.2  # IP address of ToR1
            asn: 65011           # ASN of ToR1
            # ebgpMultihop: 2
            # bfdProfile: testbfdprofile
            toReceive:
              allowed:
                mode: all        # Accept all prefixes from ToR1