# The following is in case of multiple tor connected to router-0

# router0# show ip bgp summary

# IPv4 Unicast Summary (VRF default):
# BGP router identifier 10.0.0.0, local AS number 65000 vrf-id 0
# BGP table version 6
# RIB entries 11, using 2024 bytes of memory
# Peers 2, using 1433 KiB of memory
# Peer groups 1, using 64 bytes of memory

# Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
# tor0(net0)      4      65010       416       418        0    0    0 00:20:26            2        7 N/A
# tor1(net1)      4      65011       415       416        0    0    0 00:20:25            2        7 N/A

# Total number of neighbors 2


# tor0# show ip bgp summary

# IPv4 Unicast Summary (VRF default):
# BGP router identifier 10.0.0.1, local AS number 65010 vrf-id 0
# BGP table version 7
# RIB entries 11, using 2024 bytes of memory
# Peers 3, using 2149 KiB of memory
# Peer groups 2, using 128 bytes of memory

# Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
# router0(net0)   4      65000       521       520        0    0    0 00:25:38            5        7 N/A
# 10.0.1.2        4          0         0         0        0    0    0    never       Active        0 N/A
# 10.0.2.2        4          0         0         0        0    0    0    never       Active        0 N/A

# Total number of neighbors 3


# tor1# show ip bgp summary

# IPv4 Unicast Summary (VRF default):
# BGP router identifier 10.0.0.2, local AS number 65011 vrf-id 0
# BGP table version 7
# RIB entries 11, using 2024 bytes of memory
# Peers 3, using 2149 KiB of memory
# Peer groups 2, using 128 bytes of memory

# Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
# router0(net0)   4      65000       501       501        0    0    0 00:24:38            5        7 N/A
# 10.0.3.2        4          0         0         0        0    0    0    never      Connect        0 N/A
# 10.0.4.2        4          0         0         0        0    0    0    never       Active        0 N/A

# Total number of neighbors 3

apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: bgp-peer-tor0
  namespace: metallb-system
spec:
  # peerAddress: 172.20.20.6  # Change this to your router's IP
  peerAddress: 10.0.1.2  # Change this to your router's IP
  # peerASN: 65000  # ASN of your router or another FRR instance
  peerASN: 65010  # ASN of your router or another FRR instance
  myASN: 65000  # Private ASN for MetalLB
  bfdProfile: testbfdprofile
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: bgp-peer-tor1
  namespace: metallb-system
spec:
  # peerAddress: 172.20.20.8  # Change this to your router's IP
  peerAddress: 10.0.2.2  # Change this to your router's IP
  # peerASN: 65000  # ASN of your router or another FRR instance
  peerASN: 65011  # ASN of your router or another FRR instance
  myASN: 65000  # Private ASN for MetalLB
  bfdProfile: testbfdprofile