resources:
- deploy.yaml
- svc.yaml

commonLabels:
  name: web-app

namePrefix: 
  base-

nameSuffix: 
  -v1

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: index-html-config
    behavior: create
    files: 
      - index.html
