apiVersion: apps/v1
kind: Deployment
metadata:
  name: act-runner
  namespace: gitea
spec:
  replicas: 2
  selector:
    matchLabels:
      app: act-runner
  template:
    metadata:
      labels:
        app: act-runner
    spec:
      containers:
      - name: act-runner
        image: docker.io/gitea/act_runner:nightly
        args:
        - "runner"
        - "--name"
        - "gitea-runner"
        env:
        - name: GITEA_URL
          value: "http://172.21.0.3:31002" # Update with your Gitea URL
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: act-runner-secret
              key: RUNNER_TOKEN
        - name: RUNNER_WORKDIR
          value: "/tmp/runner-workdir"
        volumeMounts:
        - mountPath: /tmp/runner-workdir
          name: workdir
      volumes:
      - name: workdir
        emptyDir: {}
