# Then create an IngressRouteTCP for ArgoCD
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: argocd-server-tcp
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`argocd.local.com`)
      services:
        - name: argocd-server
          port: 443
