apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: prod

namePrefix: 
  prod-overlay-

patches:
  - path: patch.yaml

nameSuffix: 
  -prod-v2

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: index-html-config
    behavior: replace
    files: 
      - index.html