apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: dev

namePrefix: 
  dev-overlay-

nameSuffix: 
  -dev-v2

patches:
  - path: patch.yaml

generatorOptions:
  disableNameSuffixHash: true  

configMapGenerator:
  - name: index-html-config
    behavior: replace
    files: 
      - index.html