---
# Source: webapp1/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  namespace: dev  
  labels:
    app.kubernetes.io/name: mywebapp
spec:
  selector:
    app.kubernetes.io/name: mywebapp
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  # type: LoadBalancer
