---
apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
  namespace: default  

spec:
  # selector:
  #   name: web-app1
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP