apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-issued-cert
  namespace: cert-manager
spec:
  secretName: letsencrypt-prod-account-key
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: registry.harbor.com
  dnsNames:
  - registry.harbor.com