apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email used for ACME registration
    email: anand.nande@gmail.com
    # Name of the secret to store the private key
    privateKeySecretRef:
      name: letsencrypt-account-key
    # Enable the HTTP01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx  # Change to your Ingress class if different
    # solvers:
    # - selector: {}
    #   http01:
    #     ingress:
    #       ingressClassName: nginx