apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-sign-cert
spec:
  secretName: self-sign-secret
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
  commonName: argocd.demo.com
  dnsNames:
  - argocd.demo.com
